service_name: travis-ci

env:
  global:
    - secure: cX7o0KDqZFGMn+wZEF/LGUwyn/YETyCNOvwLLq+SfGNUwuK/4CsoCBwB1aV5ewgW7yp14iDvCCF0nw/vYJBrToY9otYqvqSvuwb1/n81J/T5V4K0q9tiYGrMUqz7wZWlEgC+YyduK9Mj6dtTUsNu9I6Ov3DgxIJHMKUGUpzHFWg=
